### ISSUE TITLE
Synapse for 0.3.6

### ISSUE THREAD

**Issue by k0gen** [Start9Labs/synapse-wrapper#63]
### Service: Synapse
This issue is part of our efforts to ensure that the OS is fully ready for the service when 0.3.6 is launched.

**Current Status:**
- [ ] Works Fine
- [ ] Partial Issues
- [x] Doesn't Work

**Description:**
Synapse is currently experiencing issues with health checks in StartOS 0.3.6. The service fails to pass the necessary health checks, which could indicate deeper underlying issues affecting its functionality. Specific areas affected may include connectivity, resource usage, or service uptime.

**Tasks:**
- [ ] Investigate and identify the root cause of the health check failures.
- [ ] Address any bugs or configuration issues leading to the health check failures.
- [ ] Re-test to ensure that Synapse passes all health checks.
- [ ] Ensure all features are tested and functioning as expected.

**Comment by k0gen** [comment]
### Synapse Health Checks Issues
```
Federation
Error: open /data/start9/config.yaml: no such file or directory

Admin interface
Error: open /data/start9/config.yaml: no such file or directory Waiting for Synapse to finish initialization ...

User Signups Off
Error: open /data/start9/config.yaml: no such file or directory User signups should be disabled when not in use 
```

Logs
```
2024-08-10T09:02:04+02:00  Error: docker_entrypoint.sh exited with code 1
2024-08-10T09:02:04+02:00      at ChildProcess.<anonymous> (/usr/lib/startos/init/node_modules/@start9labs/start-sdk/cjs/lib/mainFn/CommandController.js:38:35)
2024-08-10T09:02:04+02:00      at ChildProcess.emit (node:events:519:28)
2024-08-10T09:02:04+02:00      at ChildProcess._handle.onexit (node:internal/child_process:294:12)
2024-08-10T09:02:04+02:00  Filesystem I/O Error: No such file or directory (os error 2)
2024-08-10T09:02:04+02:00  Error: docker_entrypoint.sh exited with code 2
2024-08-10T09:02:04+02:00      at ChildProcess.<anonymous> (/usr/lib/startos/init/node_modules/@start9labs/start-sdk/cjs/lib/mainFn/CommandController.js:38:35)
```
